### ISSUE TITLE
GACGD instead of ACGD? 

### ISSUE THREAD

**Issue by wagenaartje** [comp-physics/CPINN#1]
I noticed that the GMRES-based `CGDs.GACGD` optimizer (general sum game) is used instead of  the `CGDs.ACGD` optimizer (zero-sum game), even though CPINNs play zero-sum games. I also find that the `ACGD` is slightly faster (at least in the initial learning phase). 

Is there any particular reason why `GACGD` is used? Probably because it results in a lower L2 error?

**Comment by Q1Zeng** [comment]
In our experiments we found the GMRES-based version of ACGD takes less number of forward passes to solve for the matrix inverse than the CG-based ACGD. GMRES-based version of ACGD also reaches lower L2 error.

**Comment by sbryngelson** [comment]
Closing issue as discussion has stagnated.
